version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/rootfs/webapp"
    schedule:
      interval: daily
      time: "00:00"
      timezone: "Etc/UTC"
    assignees:
      - "fredclausen"

  - package-ecosystem: "npm"
    directory: "/acarshub-typescript"
    schedule:
      interval: daily
      time: "00:00"
      timezone: "Etc/UTC"
    assignees:
      - "fredclausen"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: "Etc/UTC"
    assignees:
      - "fredclausen"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: "Etc/UTC"
    assignees:
      - "fredclausen"
