FROM node:19.6.0-slim@sha256:34211d15e360eff92c17587ff3c3d3bea3061ca3961f745fd59ab30bda954ff9 AS acarshub-typescript-builder

ENV DOCKER_BUILD="true"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

#hadolint ignore=DL3008
RUN set -xe && \
    apt-get update && \
    apt-get install -y --no-install-recommends make python3 g++ && \
    rm -rf /src/* /tmp/* /var/lib/apt/lists/*

COPY acarshub-typescript/package.json /acarshub-typescript/package.json
COPY acarshub-typescript/package-lock.json /acarshub-typescript/package-lock.json

RUN set -xe && \
    pushd /acarshub-typescript && \
    npm install

COPY acarshub-typescript/ /acarshub-typescript/

RUN set -xe && \
    pushd /acarshub-typescript && \
    mkdir -p ../rootfs/webapp/static/js/ && \
    npm run build && \
    npm run installer
