name: Test PR

# FIXME: Can we not build either job if stuff has been unchanged since last commit for that job?
# FIXME: Use branch name for tagging docker build
on:
  pull_request:
    branches:
      - main
    paths:
      - "acarshub-typescript/**"
      - "Dockerfile.acarshub"
      - "Dockerfile.acarshub-nextgen"
      - "rootfs/**"
      - ".github/test-pr.yml"
      - "version$"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy_ghcr_nextgen_test:
    name: Deploy ACARS Hub Next Gen Base Image
    runs-on: ubuntu-latest

    steps:
      # Check out our code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v14.3
        with:
          files: |
            Dockerfile.nextgen
            .github/test-pr.yml
            rootfs/webapp/requirements.txt

      - name: Login to ghcr.io
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Get metadata from repo
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Set up QEMU for multi-arch builds
      - name: Set up QEMU
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/setup-qemu-action@v1

      # Set up buildx for multi platform builds
      - name: Set up Docker Buildx
        id: buildx
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v1

      # Build & Push Dockerfile (only push if this action was NOT triggered by a PR)
      - name: Build & Push ghcr.io/sdr-enthusiasts/docker-acarshub:nextgen-test
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.nextgen
          no-cache: true
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm/v6,linux/arm64
          push: true
          tags: ghcr.io/sdr-enthusiasts/docker-acarshub:nextgen-test
          labels: ${{ steps.meta.outputs.labels }}

  deploy_ghcr_latest_test:
    name: Deploy to latest to dockerhub
    runs-on: ubuntu-latest
    needs: [deploy_ghcr_nextgen_test]
    steps:
      # Check out our code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v14.3
        with:
          files: |
            Dockerfile.nextgen
            Dockerfile.acarshub
            acarshub-typescript/**
            rootfs/**
            .github/test-pr.yml
            version$

      - name: Get status of next file
        id: changed-file-nextgen
        uses: tj-actions/changed-files@v14.3
        with:
          files: |
            Dockerfile.nextgen

      - name: Get version tag from file
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "VERSION_TAG=$(sed '1!d' ./version)" >> $GITHUB_ENV
          echo "VERSION_TAG_DOCKER=$(sed '2!d' ./version)" >> $GITHUB_ENV

      # Show version tag
      - name: Show version tag
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "ACARS Hub Version: ${{ env.VERSION_TAG }}"
          echo "ACARS Hub Docker Version: ${{ env.VERSION_TAG_DOCKER }}"

      # Set version tag in webapp
      - name: Patch webapp with VERSION_TAG
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          sed -i 's/Pre-Release/ACARS Hub Version: ${{ env.VERSION_TAG }}/' ./acarshub-typescript/src/helpers/menu.ts

      - name: Create version file
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "${{ env.VERSION_TAG }}" >> ./rootfs/acarshub-version

      - name: Login to ghcr.io
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Get metadata from repo
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Set up QEMU for multi-arch builds
      - name: Set up QEMU
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/setup-qemu-action@v1

      # Set up buildx for multi platform builds
      - name: Set up Docker Buildx
        id: buildx
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v1

      # build acarshub typescript

      - name: Build ACARSHub typescript
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        working-directory: ./acarshub-typescript
        run: |
          npm install
          npm run build
          mkdir -p ./webapp/static/images
          mkdir -p ./webapp/static/js
          mkdir -p ./webapp/static/sounds
          mkdir -p ./webapp/templates
          cp -r ./dist/static/images ./webapp/static/
          cp -r ./dist/static/sounds ./webapp/static/
          cp -r ./dist/static/js ./webapp/static/
          mv ./dist/static/index.html ./webapp/templates/
          tar cvfz webapp.tar.gz ./webapp
          cp webapp.tar.gz ../webapp.tar.gz

      - name: Patch Dockerfile if Nextgen was built for this branch
        if: steps.changed-file-nextgen.outputs.any_changed
        run: sed -i "s/^FROM ghcr.io\/sdr-enthusiasts\/docker-acarshub:nextgen/FROM ghcr.io\/sdr-enthusiasts\/docker-acarshub:nextgen-test/g" Dockerfile.acarshub

      # Build & Push Dockerfile (only push if this action was NOT triggered by a PR)
      - name: Build & Push ghcr.io/sdr-enthusiasts/docker-acarshub:test
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.acarshub
          no-cache: true
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm/v6,linux/arm64
          push: true
          tags: ghcr.io/sdr-enthusiasts/docker-acarshub:test
          #tags: ghcr.io/sdr-enthusiasts/docker-acarshub:test-${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          labels: ${{ steps.meta.outputs.labels }}
